### ISSUE TITLE
Filtering files in directorry based on extension

### ISSUE THREAD

**Issue by wiz21b** [fluxxcode/egui-file-dialog#122]
Hello,

I'd like to have directory filtering based on extensions.

Have you already looked into it ? If not, do you mind if I try to do it in a fork ?

stF

**Comment by fluxxcode** [comment]
Hi, thanks for the issue.

Filtering based on file extensions is already planned, but I haven't been able to further look into it yet.
However, I already have ideas. It should be possible to add several file filters from the backend, which the user can then select in a drop down at the bottom right. (Just like in most other file dialogs)
```rust
FileDialog::default()
    .add_file_filter("PNG files", Arc::new(|path| path.extension().unwrap_or_default() == "png"))
    .add_file_filter("JPG files", Arc::new(|path| path.extension().unwrap_or_default() == "jpg"))
    ...
```

You are welcome to implement a first iteration in a PR :)

**Comment by fluxxcode** [comment]
You can use `FileDialog::set_file_icon` as a reference for file filters.

**Comment by wiz21b** [comment]
Made a PoC here: https://github.com/wiz21b/egui-file-dialog

I have reused the IconFilter struct but I find it awkwards... Rename it ? Make a copy of it ? Dunno

There's no GUI for that and frankly, I'm not sure to know how to proceed :-)

**Comment by fluxxcode** [comment]
Some points:
- Yep, you don't want to use the struct `IconFilter` directly, but your own. For example:
  ```rust
    pub struct FileFilter {
        /// The display name of the filter.
        pub name: String,
        /// Sets a filter function that checks whether a given Path matches the criteria for this fiter.
        pub filter: Filter<Path>,
    }
  ```
- The files should not be filtered when loading a directory (`load_directory`), but rather when iterating over an already loaded directory (`DirectoryContent::filtered_iter`). Otherwise, every time the user selects a different filter, we have to reload the entire directory, which takes too long.

I have some time today. If you want, I can implement it with the UI part and then you can say what you are still missing or what other features you would like :)

**Comment by fluxxcode** [comment]
File filters are now implemented on develop with the PR https://github.com/fluxxcode/egui-file-dialog/pull/124

Let me know if you have any other suggestions :)
