### ISSUE TITLE
FileDialog clone

### ISSUE THREAD

**Issue by David-OConnor** [fluxxcode/egui-file-dialog#141]
Would it be possible to Derive Clone for `FileDialog`? Would save repetitive code when setting up complicated dialogs. Ty!

**Comment by fluxxcode** [comment]
Hi, I think if I remember correctly, it is not that easy to implement clone because of some data types.

If you want to configure multiple FileDialog objects with the same or almost the same values, you can use `FileDialogConfig` and `FileDialog::with_config`. Then you don’t have to configure each object manually.

Let me know if this works for you!

**Comment by David-OConnor** [comment]
Perfect; solved; ty!
