### ISSUE TITLE
I found the path is not correct for the case of the C drive.

### ISSUE THREAD

**Issue by nil-is-lin** [fluxxcode/egui-file-dialog#59]
The following the what i get:

> Selected file: Some("\\\\?\\C:\\Users\\nil_l\\Documents\\DSeeTem\\minifiles.ini"),
> Selected file: Some("D:\\Amesim\\LMS_RLM_Server\\LMS.lic")
> Selected file: Some("E:\\rust_workspace\\egui-test\\Cargo.toml")
> Selected file: Some("F:\\nil_Blog\\nil_all.bib")

I wonder what might be causing this?

**Comment by fluxxcode** [comment]
Hi, thanks for your issue!

This is actually the correct behavior since `std::fs::canonicalize` is used to generate the absolute path from relative paths.

See the Rust Docs:
https://doc.rust-lang.org/std/fs/fn.canonicalize.html#

And the Windows Docs:
https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces

However, I'm currently unsure why this only happens with the C directory. I'll have to take a closer look.
Although I'm not sure whether I should keep using `std::fs::canonicalize` and instead also allow relative paths to be used.

**Comment by nil-is-lin** [comment]
Thank you very much for your reply, your work has helped me a lot.

**Comment by fluxxcode** [comment]
> Thank you very much for your reply, your work has helped me a lot.

I'm glad I could help you out :D

Let me know if you have any other bugs or features requests!

**Comment by fluxxcode** [comment]
I have now fixed that not every path on Windows has the `\\?\` prefix and not every path has been canonicalized.

I will also add the feature that `fs::canonicalize` can be disabled to be able to use relative paths and prevent the prefix on Windows.
