### ISSUE TITLE
Automatically search upon typing

### ISSUE THREAD

**Issue by aymey** [fluxxcode/egui-file-dialog#89]
The search bar should be automatically focused when typing so you don't have to manually click on it to filter out files.

**Comment by fluxxcode** [comment]
Hi, thanks for the Issue!

The feature is already planned in the following issue: https://github.com/fluxxcode/egui-file-dialog/issues/70

@crumblingstatue has already written an experimental implementation for this:
https://github.com/crumblingstatue/egui-file-dialog/commit/5f148ae57371cc6bd16fac8c7266950cce5161d6

But I don't know what the current status is.

There are also a few points about when we want to avoid the behavior:
- When the user presses Ctrl or Shift so that we can implement Key bindings in the future
- When the user is already in any input field

**Comment by crumblingstatue** [comment]
> But I don't know what the current status is.

It was rebased against the latest dev branch yesterday.

> * When the user presses Ctrl or Shift so that we can implement Key bindings in the future
> 
> * When the user is already in any input field

I can try and make it fit these requirements and clean things up and open a pull request

**Comment by fluxxcode** [comment]
This is working well so far. But I think we should allow to automatically enter search while Shift is pressed.
Otherwise it doesn't work if the first letter is to be capitalized 🤔

**Comment by aymey** [comment]
Oops, i didn't realise that, fixed in https://github.com/crumblingstatue/egui-file-dialog/pull/1/commits/dffed3f6dbed0fc9d5cac026da5585b63e4ddd57.

**Comment by fluxxcode** [comment]
This works really great now! Will merge the changes once @crumblingstatue creates a PR :)
